import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import ModalWrapper from "@/app/ModalWrapper";
import { getUser } from "@/app/actions/getUser";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialUser={user}>
          {children}
          <ModalWrapper modal={modal} />
        </Providers>
      </body>
    </html>
  );
}
